kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkin-admin-sa-role-binding
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins-admin-sa
  namespace: jenkins
  apiGroup: ""
roleRef:
  kind: Role
  name: jenkins-admin-sa-role
  apiGroup: ""  
