---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-admin-sa
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        volumeMounts:
        - name: nfs-volume
          mountPath: /var/jenkins_home
      volumes:
        - name: nfs-volume
          nfs: 
            # URL for the NFS server
            server: 192.168.7.11
            path: /home/public/var/jenkins/home
